<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126163848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "like" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_super_like BOOLEAN NOT NULL, from_user_id INT NOT NULL, to_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC6340B32130303A ON "like" (from_user_id)');
        $this->addSql('CREATE INDEX IDX_AC6340B329F6EE60 ON "like" (to_user_id)');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_seen BOOLEAN NOT NULL, match_id INT NOT NULL, sender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F2ABEACD6 ON message (match_id)');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('CREATE TABLE presence_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_online BOOLEAN NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9691D40CA76ED395 ON presence_status (user_id)');
        $this->addSql('CREATE TABLE typing_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_typing BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, from_user_id INT NOT NULL, to_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EDA38C92130303A ON typing_status (from_user_id)');
        $this->addSql('CREATE INDEX IDX_4EDA38C929F6EE60 ON typing_status (to_user_id)');
        $this->addSql('CREATE TABLE user_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user1_id INT NOT NULL, user2_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98993E5D56AE248B ON user_match (user1_id)');
        $this->addSql('CREATE INDEX IDX_98993E5D441B8B65 ON user_match (user2_id)');
        $this->addSql('ALTER TABLE "like" ADD CONSTRAINT FK_AC6340B32130303A FOREIGN KEY (from_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "like" ADD CONSTRAINT FK_AC6340B329F6EE60 FOREIGN KEY (to_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F2ABEACD6 FOREIGN KEY (match_id) REFERENCES user_match (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE presence_status ADD CONSTRAINT FK_9691D40CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE typing_status ADD CONSTRAINT FK_4EDA38C92130303A FOREIGN KEY (from_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE typing_status ADD CONSTRAINT FK_4EDA38C929F6EE60 FOREIGN KEY (to_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_match ADD CONSTRAINT FK_98993E5D56AE248B FOREIGN KEY (user1_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_match ADD CONSTRAINT FK_98993E5D441B8B65 FOREIGN KEY (user2_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "like" DROP CONSTRAINT FK_AC6340B32130303A');
        $this->addSql('ALTER TABLE "like" DROP CONSTRAINT FK_AC6340B329F6EE60');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F2ABEACD6');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE presence_status DROP CONSTRAINT FK_9691D40CA76ED395');
        $this->addSql('ALTER TABLE typing_status DROP CONSTRAINT FK_4EDA38C92130303A');
        $this->addSql('ALTER TABLE typing_status DROP CONSTRAINT FK_4EDA38C929F6EE60');
        $this->addSql('ALTER TABLE user_match DROP CONSTRAINT FK_98993E5D56AE248B');
        $this->addSql('ALTER TABLE user_match DROP CONSTRAINT FK_98993E5D441B8B65');
        $this->addSql('DROP TABLE "like"');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE presence_status');
        $this->addSql('DROP TABLE typing_status');
        $this->addSql('DROP TABLE user_match');
    }
}
